name: Maven Build and Docker Hub

on:
   workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: zulu

      - name: Build with Maven
        run: mvn clean install
        
        
      - name: Build and Push Docker Image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker build -t nelvindc/take-home:tag1 .
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker push nelvindc/take-home:tag1